version: '3'
services:
  db:
    image: mysql:8.0.21
    container_name: qr-db
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - ./mysql/conf:/etc/mysql/conf.d # 設定ファイル
      - ./mysql/data:/var/lib/mysql
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'sample_db'
    # platform: linux/x86_64
    restart: always

  view:
    build: ./view
    container_name: qr-view
    volumes:
      - ./view:/app
    command: ["node", "index.js"]
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  api:
    build: ./api
    container_name: qr-api
    volumes:
      - ./api:/go/src/work
    #シェルスクリプトを実行するコマンド
    command: "./start.sh"
    ports:
      - "1323:1323"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_started

volumes:
  go_path:
